stages:
  - build
  - deploy

variables:
  NODE_VERSION: '20.19.0'

# Build stage - runs on every push
build:
  stage: build
  image: node:${NODE_VERSION}
  cache:
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

# Deploy using dpl instead of git push
deploy-production:
  stage: deploy
  image: ruby:3.1-alpine
  before_script:
    - apk add --no-cache build-base curl git
    - gem install dpl
  script:
    - echo "Deploying to production app - leo-web-frontend"
    - dpl --provider=heroku --app=leo-web-frontend --api-key=$HEROKU_API_KEY --skip-cleanup
  environment:
    name: production
    url: https://leo-web-frontend-84a7518ad9a1.herokuapp.com
  needs: ['build']
